      SUBROUTINE PINVARIANTS(A,INV4,NDI,ST,LAMBDA,BARLAMBDA,DET)
C>    AND 4TH PSEUDO-INVARIANTS OF A TENSOR
      IMPLICIT NONE
      INCLUDE 'PARAM_UMAT.INC'
C
      INTEGER NDI,I,J
      DOUBLE PRECISION A(NDI,NDI),DET,SCALE1,ST(NDI,NDI),LAMBDA
      DOUBLE PRECISION BARLAMBDA,INV4
C
        INV4=ZERO
      DO I=1,NDI
        DO J=1, NDI
            INV4=INV4+A(I,J)*ST(I,J)
        ENDDO
      ENDDO
C     STRETCH
      SCALE1=DET**(-ONE /THREE)
      BARLAMBDA=DSQRT(INV4)
      LAMBDA=BARLAMBDA/SCALE1
C
      RETURN
      END SUBROUTINE PINVARIANTS
