      SUBROUTINE RELAX(QV,HV,AUX1,HV0,PKISO,DTIME,TAU,TETA,NDI)
C>    VISCOUS DISSIPATION: STRESS RELAXATION TENSORS
      IMPLICIT NONE
      INCLUDE 'PARAM_UMAT.INC'
C
      INTEGER I1,J1,NDI
      DOUBLE PRECISION QV(NDI,NDI),HV(NDI,NDI),PKISO(NDI,NDI),
     1                 HV0(NDI,NDI)
      DOUBLE PRECISION DTIME,TETA,TAU,AUX1,AUX
C
      QV=ZERO
      HV=ZERO

       AUX=DEXP(-DTIME*((TWO*TAU)**(-ONE)))
       AUX1=TETA*AUX
       DO I1=1,NDI
        DO J1=1,NDI
         QV(I1,J1)=HV0(I1,J1)+AUX1*PKISO(I1,J1)
         HV(I1,J1)=AUX*(AUX*QV(I1,J1)-TETA*PKISO(I1,J1))
        END DO
       END DO
C      
      RETURN
      END SUBROUTINE RELAX
