      SUBROUTINE DEFFIL(LAMBDA,M,M0,F,NDI)
C>      SINGLE FILAMENT: STRETCH AND DEFORMED DIRECTION
      IMPLICIT NONE
      INCLUDE 'PARAM_UMAT.INC'
C
      INTEGER NDI,I1,J1
      DOUBLE PRECISION F(NDI,NDI),M(NDI),M0(NDI)
      DOUBLE PRECISION AUX,LAMBDA      
C
      LAMBDA=ZERO
      DO I1=1,NDI
        AUX=ZERO
       DO J1=1,NDI
         AUX=AUX+F(I1,J1)*M0(J1)
       END DO
         M(I1)=AUX
      END DO
         LAMBDA=DOT_PRODUCT(M,M)
         LAMBDA=SQRT(LAMBDA)
C
      RETURN
      END SUBROUTINE DEFFIL
