      SUBROUTINE HFILFIC(H,HH,PP,LAMBDA,M,RW,NDI)
C>      NON-AFFINE NETWORK: STRUCTURE TENSORS
      IMPLICIT NONE
      INCLUDE 'PARAM_UMAT.INC'
C
      INTEGER NDI,I1,J1,K1,L1
      DOUBLE PRECISION HH(NDI,NDI,NDI,NDI),M(NDI),H(NDI,NDI)
      DOUBLE PRECISION RW,LAMBDA,AUX0,AUX,PP,PI,AUX1
C
      PI=FOUR*ATAN(ONE)
      AUX0=FOUR*PI
      AUX=(LAMBDA**(PP-TWO))*RW
      AUX1=(PP-TWO)*(LAMBDA**(PP-FOUR))*RW
C      
      DO I1=1,NDI
       DO J1=1,NDI
        H(I1,J1)=AUX*M(I1)*M(J1)
        DO K1=1,NDI
         DO L1=1,NDI
          HH(I1,J1,K1,L1)=AUX1*M(I1)*M(J1)*M(K1)*M(L1)
         END DO
        END DO
       END DO
      END DO
C
      RETURN

      END SUBROUTINE HFILFIC
