      SUBROUTINE SIGFILFIC(SFIC,RHO,LAMBDA,DW,M,RW,NDI)
C>    SINGLE FILAMENT:  'FICTICIUOUS' CAUCHY STRESS 
      IMPLICIT NONE
      INCLUDE 'PARAM_UMAT.INC'
C
      INTEGER NDI,I1,J1
      DOUBLE PRECISION SFIC(NDI,NDI),M(NDI)
      DOUBLE PRECISION RHO,AUX,DW,RW,LAMBDA
C
      AUX=RHO*LAMBDA**(-ONE)*RW*DW
      DO I1=1,NDI
       DO J1=1,NDI
        SFIC(I1,J1)=AUX*M(I1)*M(J1)
       END DO
      END DO
C
      RETURN
      END SUBROUTINE SIGFILFIC
